# Generated by Django 2.0 on 2020-03-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='images',
            new_name='image',
        ),
    ]
